---
pagetitle : Eduard F. Martínez-González
---

<br>  </br> <!--- Agrega lineas en blanco --->

# Working papers

<p>  </p> <!--- Agrega una linea en blanco --->

<!------------- Documento 1 ------------->

<strong style="color:black;font-size:22px;"> Motorcycle restrictions and their effects on crime in Colombia </strong> [[PDF]](https://eduard-martinez.github.io/research/motorycle_restrictions/motorycle_restrictions.pdf) [[SSNR]](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3659686) (with [Michael Weintraub](http://michael-weintraub.squarespace.com) and [Leonardo Bonilla](https://investiga.banrep.gov.co/es/profile/76))

 <p align="justify"> **Abstrac:** Although motorcycle restrictions have been adopted to reduce crime in more than 25 Colombian cities, no empirical evidence exists to demonstrate their effectiveness. This document evalutes the impact of six of these restrictions. To identify their causal effects, we estimate difference-in-differences models that exploit spatial and temporal variation in their implementation and georeferenced crime data. We find neither large nor lasting effects of these measures on crime. Given the high costs of assuring compliance with these measures and the costs they impose on citizens, local authorities should seek out other public policy alternatives to improve citizen security. </p>

<!------------- Documento 2 ------------->

<strong style="color:black;font-size:22px;">Payroll taxes, wage rigidities and youth unemployment: Evidence from colombian labor market</strong> [[PDF]](https://eduard-martinez.github.io/research/youth_unemployment/youth_unemployment.pdf) (with [Danilo Aristizabal](http://danilo-aristizabal.github.io))

<p align="justify"> **Abstrac:** This paper studies the effect on youth employment of a payroll tax cut for new hires young workers under the age of 28 in Colombia. We exploit differential degrees of exposure to wage rigidities to identify the effect. We measure an individual’s exposure to wage rigidities as the distance, in the city in which the individual lives, from the median salary by educational level with respect to the minimum wage. We have two different treatment groups and use a difference-in-difference model. The effect of reduced payroll taxes is asymmetric for youth who earn below and above the minimum wage. Reducing payroll taxes increased youth labor participation, rather than reducing informality. </p>

<!------------- Documento 3 ------------->

<strong style="color:black;font-size:22px;"> Economics Shocks and Crime: Evidenmce From Colombia </strong> [[PDF]](https://eduard-martinez.github.io/research/jmp/economics_shocks.pdf) 

<p align="justify"> **Abstrac:** This paper studies the effect of a negative economic shock on crime. I collect criminal records for 165,000 users of an informal financial sector firm that was closed in Colombia at the end of 2008. I exploit the exogenous variation produced by the intervention in users who had deposits with an expiration date in the days close to the firm's closing date. The results suggest an increase in the number of legal proceedings for those suffering the negative economic shock, but this effect is concentrated only in those on the right-hand side of the distribution of unrecovered investments. </p>

<!------------- Documento 4 ------------->

<strong style="color:black;font-size:22px;">School Education for Inclusion and Social Transformation in the Colombian Caribbean</strong> [[PDF]](https://eduard-martinez.github.io/research/caribbean_education/caribbean_education.pdf) [[DTSER-BANREP]](https://www.banrep.gov.co/es/publicaciones/documento-de-trabajo-economia-regional-y-urbana-263) (with [Leonardo Bonilla](https://investiga.banrep.gov.co/es/profile/76))

<p align="justify"> **Abstrac:** The Caribbean Region of Colombia is particularly behind in terms of school coverage and quality. This paper proposes a set of policies that provide a big push to the public education system and allow closing the gap by 2030. Policies are organized into four categories: Preschool education, full-day schooling, teacher training and institutional capacity. The total cost of the intervention is estimated at 6,274 million dollars over 12 years, of which 2,114 correspond to investments and 4,160 to the additional recurrent expenditures of the education system. </p>

<p>  </p> <!--- Agrega una linea en blanco --->

<!--- # Other Publications

<strong style="color:black;font-size:22px;">School Education for Inclusion and Social Transformation in the Colombian Caribbean</strong> [[PDF]](https://eduard-martinez.github.io/research/caribbean_education/caribbean_education.pdf) [[DTSER-BANREP]](https://www.banrep.gov.co/es/publicaciones/documento-de-trabajo-economia-regional-y-urbana-263) (with [Leonardo Bonilla](https://investiga.banrep.gov.co/es/profile/76))

<p align="justify"> **Abstrac:** The Caribbean Region of Colombia is particularly behind in terms of school coverage and quality. This paper proposes a set of policies that provide a big push to the public education system and allow closing the gap by 2030. Policies are organized into four categories: Preschool education, full-day schooling, teacher training and institutional capacity. The total cost of the intervention is estimated at 6,274 million dollars over 12 years, of which 2,114 correspond to investments and 4,160 to the additional recurrent expenditures of the education system. </p> --->

<br>  </br> <!--- Agrega lineas en blanco --->

<br>  </br> <!--- Agrega lineas en blanco --->